# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Docker-Build-Ranger

on:
  workflow_dispatch:
    inputs:
      rangerBranch:
        description: 'ranger branch'
        required: true
        default: 'master'
        type: choice
        options:
          - master
          - ranger-2.3
      rangerVersion:
        description: 'latest'
        required: true
        default: 'latest'
        type: choice
        options:
          - latest
          - 2.3.0
env:
  HUB: ghcr.io/flowerfine/ranger
  RANGER_BRANCH: ${{ inputs.rangerBranch }}
  RANGER_VERSION: ${{ inputs.rangerVersion }}
  DOCKER_BUILDKIT: 1
  MAVEN_OPTS: "-Xms2g -Xmx2g"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    timeout-minutes: 30
    steps:
      - name: Checkout ranger-kubernetes
        uses: actions/checkout@v3
        with:
          path: ranger-kubernetes
      - name: Checkout ranger
        uses: actions/checkout@v3
        with:
          repository: apache/ranger
          ref: ${{ env.RANGER_BRANCH }}
          path: ranger
      - name: Setup JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: temurin
          cache: maven
      - name: Build with Maven
        timeout-minutes: 360
        run: cd ranger && mvn -DskipTests=true -DskipDocs clean package
      - name: Log in to the Container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ env.HUB }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2